---
- name: "Disable SELinux"
  selinux:
    state: "disabled"
  register: selinux_disabled

- name: "Reboot node to deactivate selinux"
  reboot:
  when: selinux_disabled.changed

# - name: "Install vim"
#   package:
#     name: "vim"
#     state: "present"

- name: "Install basic packages"
  package:
    name: "{{ item }}"
    state: "present"
  with_items:
    - vim
    - tmux

- name: "Install host specific packages"
  package:
    name: "{{ item }}"
    state: "present"
  with_items: "{{ common__host_packages }}"
  when: common__host_packages is defined

- name: "Deploy public keys"
  authorized_key:
    user: "centos"
    state: "present"
    key: "{{ common__authorized_keys }}"
  when: common__authorized_keys is defined

- name: "Disallow agent forwarding"
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?AllowAgentForwarding'
    line: "AllowAgentForwarding no" 
  register: sshd_config_changed

- debug:
    msg: "{{ sshd_config_changed }}"

- name: "Restart ssh daemon"
  service:
    name: "sshd"
    state: "restarted"
  when: sshd_config_changed.changed
