---
#
# ansible-playbook -i inventory/preproduction/hosts.yml --extra-vars="@credentials.yml" databases.yml --ask-vault-pass
#
- hosts: databases
  become: true

  roles:
    - common
    - bertvv.mariadb

